#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Feel free to delete this file.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

## Output uwt settings.
## https://phabricator.whonix.org/T73
if test -x /usr/bin/uwt_settings_show ; then
   /usr/bin/uwt_settings_show
fi
